import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container, CssBaseline } from "@mui/material";
import Header from "./header/header";
import Providers from "./providers";
import authenticated from "./auth/authenticated";
import logout from "./auth/logout";
import getMe from "./get-me";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = authenticated();
  let isAdmin = false;
  if (isAuthenticated) {
    const user = await getMe() as { role?: string };

    isAdmin = user?.role === "ADMIN";
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers authenticated={isAuthenticated} isAdmin={isAdmin}>
          <CssBaseline />
          <Header logout={logout} />
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  );
}
